### ISSUE TITLE
Switch to rust-lang/rust:nightly-slim image?

### ISSUE THREAD

**Issue by hawkrives** [frog-pond/data-server#13]
https://hub.docker.com/r/rustlang/rust/tags

I feel like you evaluated this, @rye, but I don't remember why you opted against it in the end. Looks like it's kept _fairly_ up to date, with a "last update" of 20 hours ago, for what that's worth.

A large part of the build time in this repo is installing rust, so that's why I went looking :-)

**Comment by rye** [comment]
I preferred to use the default library image, primarily.

If we're fine using this one instead, I'm alright with that.

**Comment by hawkrives** [comment]
I'll put up a PR switching to that, just to see the time difference (ftr, a [recent build](https://circleci.com/workflow-run/69f3ed5b-7497-4c27-b6a4-6dcb951c40d7) took 7:39 to deploy to docker.)
