### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by rye** [frog-pond/data-server#15]
I've run into a couple of road blocks locally where I'm trying to decide between making this code more modular and library-like and making it more reusable and publishable on crates.io.

Our plan was to make this more general purpose—an API that lets people propose building hours (or general data changes) which are stored in a Git backing store as YAML files.

So I'm trying to think of project name ideas, for something that's more memorable and could be a unique name. `data-server` just doesn't cut it, I think.

How do we feel about any of the following ideas? (Add your own)

- `datask`
- `openh`
- `gith`

**Comment by drewvolz** [comment]
> * `datask`
> * `openh`
> * `gith`

I like your suggestions. I'll throw some ideas down here, too.

* `open-data`
* `institution-data`
* `data-data-data`
* `backbone`
* `cat-herder`
* `source-of-truth`

**Comment by hawkrives** [comment]
I kinda like data-data-data

**Comment by rye** [comment]
@rye says it's too early to think about publishing. We'll just use `data_server` for now.
